name: video_editor_demo
description: "Professional Video Editor App - Built with Clean Architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Navigation
  go_router: ^14.2.7

  # Network & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1

  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utils
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  logger: ^2.4.0
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2

  # Performance & Monitoring
  # Firebase dependencies removed

  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.3

  # Media & Video
  video_player: ^2.8.6
  image_picker: ^1.0.7
  permission_handler: ^11.3.1

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  integration_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/inter/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 700
